DeveloperAcademy-POSTECH/2024-MC3-M17-TeamMosuChalamet-iOS

Shoak/Actors/ShoakActor/UseCases/ShoakUseCase.swift, Shoak/Entity/TMProfileDTO.swift, Shoak/Entity/TMProfileVO.swift, SwiftUIView.swift
TMProfileDTO, TMProfileVO 수정했습니다.
- 이슈 티켓 : resolved #4 
Image는 서버측에서 URL(String) 형식으로 알려줄 예정입니다.
=> [fix] TMProfileDTO, TMProfileVO 수정

Shoak.xcodeproj/project.pbxproj
=> [feat] 빌드 오류 해결

InviteFriends/Assets.xcassets/Contents.json, InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/Contents.json, InviteFriends/Base.lproj/MainInterface.storyboard, InviteFriends/Info.plist, InviteFriends/MessagesViewController.swift, Shoak.xcodeproj/project.pbxproj, Shoak.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Shoak.xcodeproj/xcshareddata/xcschemes/InviteFriends.xcscheme, Shoak/Actors/AppleAdminActor/UseCases/AppleUseCase.swift, Shoak/Actors/AppleAdminActor/View/AppleLoginView.swift, Shoak/Actors/AppleAdminActor/View/MessageComposeView.swift, Shoak/Shoak.entitlements
- iMessage 기능 구현
- 이슈 티켓 : resolved #8
- 우리가 iMessage 부분 개발을 할 떄 iMessage 앱 확장 방법으로 개발을 해야 하는 것 같은데요! 그래서 수정 가능한 UI 요소들이 몇가지 정해져 있는 것 같아요. 그건 일단 메세지 UI에 담고 싶은 정보들 확정되었을 때 수정하면 될 것 같아 열린 코드(?)로 작성해 두었습니다. 언제든 수정가능합니다!
https://github.com/user-attachments/assets/2fb10dbf-f7da-4fb9-b8d9-9fd59e1ab458
https://github.com/user-attachments/assets/2a8f3e5b-8652-4b37-8564-d2fffc611ebc
=> [Feat] iMessage 구현

InviteFriends/MessagesViewController.swift, Shoak.xcodeproj/project.pbxproj
- NSLayoutConstraint 사용해서 레이아웃 구현
- Snapkit 안녕
- 친구 요청 메세지 UI 상태 구분 가능
- 이슈 티켓 : resolved #26
=> [Refactor] NSLayoutConstraint 사용하기

Shoak.xcodeproj/project.pbxproj, Shoak/Actors/ShoakActor/View/FriendListView.swift, Shoak/Common/InvitationManager.swift, Shoak/RootView.swift, Shoak/ShoakApp.swift, Shoak/Utility/ViewModifiers/AddEnvorinmentsForPreview.swift, Shoak/Utility/ViewModifiers/ClipShapeBorder.swift
iphone 용 친구 리스트 뷰를 작성하였습니다.
- 이슈 티켓 : resolved #28 
배경 ignore되는거때문에 한참 헤맸네요.. ㅠ
https://github.com/user-attachments/assets/687fdd08-b9b0-4284-8cf7-bba466d57ba2
=> [Feat] 친구 리스트 뷰

Shoak.xcodeproj/project.pbxproj, Shoak/Actors/AppleAdminActor/UseCases/AppleUseCase.swift, Shoak/Actors/AppleAdminActor/View/AppleLoginView.swift, Shoak/Actors/CommonActor/UseCases/AuthUseCase.swift, Shoak/Actors/CommonActor/View/LoginView.swift, Shoak/Actors/ShoakActor/View/FriendListView.swift, Shoak/Actors/ShoakActor/View/OnboardingView.swift, Shoak/Common/AccountManager.swift, Shoak/Common/ShoakDataManager.swift, Shoak/Entity/TMUserCredentialVO.swift, Shoak/Shoak.entitlements, Shoak/ShoakApp.swift, Shoak/ShoakAppDelegate.swift, ShoakTests/AuthUseCaseTests.swift
로그인 플로우를 명확하게 명시했습니다.
온보딩 플로우를 명확하게 명시했습니다.
디바이스 토큰을 App Delegate를 활용해서 불러옵니다.
Push Notification Capabilities를 추가했습니다.
- 이슈 티켓 : resolved #32 
https://github.com/user-attachments/assets/641a8fcf-292e-4437-8143-ba7de16412f8
=> [Feat] 로그인 플로우 & 디바이스 토큰 얻어오기

Shoak.xcodeproj/project.pbxproj, Shoak/Actors/CommonActor/View/Components/BackButton.swift, Shoak/Actors/ShoakActor/View/OnboardingView.swift, Shoak/Utility/CaseIterable+.swift
온보딩에 필요한 다음 버튼과 백버튼을 구현했습니다.
- 이슈 티켓 : resolved #34
=> [Feat] Onboarding 뷰, 백버튼

Shoak/Common/ShoakDataManager.swift, ShoakWatch Watch App/ShoakWatchApp.swift, ShoakWatch Watch App/View/WatchFriendListView.swift
사용성을 개선했습니다. 친구 리스트 불러오기할 때 에러율을 낮추고, 로딩화면을 추가했습니다.
- 이슈 티켓 : resolved #55
=> [#55] Watch 사용성 개선

Shoak.xcodeproj/project.pbxproj, Shoak/DesignSystem/Color/ColorManager.swift, ShoakWatch Watch App/ShoakWatchApp.swift, ShoakWatch Watch App/View/CircleImage.swift, ShoakWatch Watch App/View/PushNotificationPayload.apns, ShoakWatch Watch App/View/WatchFriendListView.swift, ShoakWatch Watch App/View/WatchNotificationController.swift, ShoakWatch Watch App/View/WatchNotificationView.swift
햅틱 수정,
포그라운드 상태에서도 알림 오도록 했습니다.
- 이슈 티켓 : resolved #57 
코드가 실행되는지 확인하고 싶어열.
어떤 햅틱이 좋을지는 좀 더 생각해봐야할 것 같아요. 멘토들 이야기 들어봐야 할 듯.
=> [#57] 노티 햅틱 3번 진동

Shoak/Actors/ShoakActor/View/DeleteFriendView.swift, Shoak/Actors/ShoakActor/View/FriendListView.swift
- 친구삭제 UI 세부 사항들 수정했습니다
- 이슈 티켓 : resolved #69
https://github.com/user-attachments/assets/e401597e-0cf2-4d83-b193-f8186b43c795
=> [Fix] 친구삭제 UI 세부사항 수정

Shoak.xcodeproj/project.pbxproj, Shoak/Actors/CommonActor/View/EditProfileView.swift, Shoak/Entity/TMDeviceTokenDTO.swift, Shoak/Network/API/TokenRefreshAPI.swift, Shoak/Network/APIClient.swift, Shoak/Network/MoyaPlugins/AddTokenPlugin.swift, Shoak/Network/Repository/TokenRefreshRepository.swift, Shoak/Network/Token/TokenManager.swift
디바이스 토큰 갱신 로직 추가
- 이슈 티켓 : resolved #68
=> [Fix] 디바이스 토큰 갱신

Shoak.xcodeproj/project.pbxproj, Shoak/Actors/ShoakActor/UseCases/SendShoakUseCase.swift, Shoak/Common/ShoakDataManager.swift, Shoak/Info.plist, ShoakWatch Watch App/View/WatchFriendListView.swift
Async Image 
- 이슈 티켓 : resolved #75
=> [Fix] AsyncImage 에러 해결

ShoakWatch Watch App/View/WatchNotificationController.swift
햅틱 
큰 진동 + 옅은 진동 + 큰 진동으로 수정했습니다. 
- 이슈 티켓 : resolved #66 
햅틱 interval 시간이나 햄틱 종류를 다양하게 조합해봤는데 임팩트에는 사실 그렇게 큰 차이가 있는 것 같지 않습니다. 더 좋은 햅틱이 있다면 바꾸는 건 쉬워서 바꾸려면 언제든 바꿔도 될 듯해요
=> [Fix] 햅틱 수정

Shoak.xcodeproj/project.pbxproj, Shoak/Actors/CommonActor/View/SettingView.swift, Shoak/Actors/ShoakActor/UseCases/UserUseCase.swift, Shoak/Common/AccountManager.swift, Shoak/Entity/TMNameDTO.swift, Shoak/Network/API/UserAPI.swift, Shoak/Network/Repository/UserRepository.swift, ShoakTests/AuthUseCaseTests.swift, ShoakTests/TokenManagerTests.swift
Lottie 아이콘 앱클립에서 안보이는 오류를 수정했습니다.
이름 수정 기능을 추가했습니다.
- 이슈 티켓 : resolved #92
=> [Fix] Lottie 아이콘 앱클립에서 안보이는 오류 수정, 이름 수정 추가

README.md
- README.md 수정
- 이슈 티켓 : resolved #84
=> [Doc] README.md 수정

Shoak/Actors/CommonActor/View/Components/BackButton.swift, Shoak/Actors/CommonActor/View/EditProfileView.swift, Shoak/Actors/CommonActor/View/LoginView.swift, Shoak/Actors/CommonActor/View/SettingView.swift, Shoak/Actors/InvitationActor/View/InviteFriendsView.swift, Shoak/Actors/ShoakActor/View/DeleteFriendView.swift, Shoak/Actors/ShoakActor/View/OnboardingView.swift, Shoak/Common/NavigationManager.swift, Shoak/Common/ShoakDataManager.swift, Shoak/Network/Token/TokenRepository.swift, ShoakWatch Watch App/PhoneConnectivityManager.swift, ShoakWatch Watch App/ShoakWatchApp.swift, ShoakWatch Watch App/View/WatchFriendListView.swift
온보딩에 프로필 수정 추가
- 이슈 티켓 : resolved #94
=> [#94] 온보딩에 프로필 수정 추가

Shoak/Actors/CommonActor/View/SettingView.swift
이름 8글자 제한 garud문 고치기
- 이슈 티켓 : resolved #94
=> [Fix] 이름 8글자 제한 guard문 고치기

Shoak/Actors/CommonActor/View/EditProfileView.swift, Shoak/Actors/CommonActor/View/SettingView.swift, Shoak/Actors/InvitationActor/View/AcceptInvitationView.swift, Shoak/Actors/ShoakActor/View/FriendListView.swift, ShoakWatch Watch App/View/WatchFriendListView.swift
Watch 친구 리스트 사진과 텍스트 간격 조정
버튼 장시간 안눌렀을 때 선택취소
사진 불러오기에서 Crash 나는거 해결
친구 초대 실패 시 오류 메세지 표시
- 이슈 티켓 : resolved #98
=> [Fix] 각종 오류 개선

Shoak.xcodeproj/project.pbxproj, Shoak/Actors/ShoakActor/View/FriendListView.swift, Shoak/Common/AccountManager.swift, Shoak/Common/NavigationManager.swift, Shoak/Info.plist, Shoak/Network/APIClient.swift, Shoak/Network/MoyaPlugins/AddTokenPlugin.swift, Shoak/Network/MoyaPlugins/LogoutPlugin.swift, Shoak/Network/MoyaPlugins/StoreTokenPlugin.swift, Shoak/Network/Repository/TokenRefreshRepository.swift, Shoak/Network/RequestInterceptor.swift, Shoak/Network/Token/TokenStorage.swift, Shoak/ShoakAppDelegate.swift, Shoak/Utility/Notification.Name+.swift, ShoakClip/Info.plist, ShoakTests/TokenManagerTests.swift, ShoakWatch Watch App/View/WatchFriendListView.swift
로그인 로직 점검 및 디바이스 토큰 로직을 점검했습니다.
- 이슈 티켓 : resolved #100
=> [Fix] 디바이스 토큰 로직 및 로그인 로직 점검

Shoak.xcodeproj/project.pbxproj, Shoak/Actors/CommonActor/View/Components/ImagePicker.swift, Shoak/Actors/CommonActor/View/SettingView.swift
- 프로필 수정 앨범 방식 변경(기본 앨범 모달 쓰는 방식으로)
- 이슈 티켓 : resolved #102
=> [Refactor] 프로필 수정 앨범 방식 변경

Shoak.xcodeproj/project.pbxproj, Shoak/Actors/CommonActor/UseCases/AuthUseCase.swift, Shoak/Actors/CommonActor/View/LoginView.swift, Shoak/Actors/ShoakActor/View/CheckMyProfileView.swift, Shoak/Actors/ShoakActor/View/Components/BottomButton.swift, Shoak/Actors/ShoakActor/View/OnboardingView.swift, Shoak/Common/AccountManager.swift, Shoak/Common/NavigationManager.swift, Shoak/Network/API/InvitationAPI.swift, Shoak/Network/Repository/AuthRepository.swift, Shoak/Network/Repository/InvitationRepository.swift, Shoak/Utility/CaseIterable+.swift
일반 로그인을 하면 바로 친구 리스트로 가게끔 수정했습니다.
- 이슈 티켓 : resolved #109 
200이 오면 로그인 성공 -> 친구리스트로
201이 오면 회원가입 성공 -> 온보딩으로
가는 코드를 프로필 수정하기 페이지의 다음 화면으로 띄워야 하므로, 상위 뷰에서 주입하는 방식으로 진행했습니다.
https://github.com/user-attachments/assets/290239fc-215d-48bc-8d45-86c6aead2f69
=> [#109] 일반 로그인 시 바로 친구 리스트로 가기

Shoak/Actors/ShoakActor/View/FriendListView.swift
- 친구 수가 최대치(20명)일 때 친구 추가 버튼 클릭하면 alert 뜨도록
- 친구 삭제해서 수 줄어들면 다시 추가 가능
- 이슈 티켓 : resolved #111
=> [Refactor] 친구 추가 버튼: 친구 수가 최대치일 때 alert 표시하도록 수정

Shoak/Actors/ShoakActor/View/OnboardingView.swift
단축어 생성 폰트 변경
- 이슈 티켓 : resolved
=> [#112] 단축어 생성 폰트 변경

Shoak/Actors/ShoakActor/View/Components/BottomButton.swift, Shoak/Actors/ShoakActor/View/OnboardingView.swift, Shoak/Common/Localization/Localizable.xcstrings
온보딩에 번역 반영 안된 것 수정했습니다.
- 이슈 티켓 : resolved #117
=> [#117] 온보딩 번역 안된거 수정
